# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Documenting my journey into infosec with write-ups for eJPT, eCPPTv2, OSCP, CTFs and some occasional shitposts.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://a56z.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: a56z_
github_username:  a56z

# Google Analytics
google_analytics: G-ELHB6X3W1V

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.markdown
  - code.md
  - snippets.md
  - shitposts.md

style: hacker

footer: 'follow me on <a href="https://twitter.com/a56z__/">twitter</a>'

# Build settings
#markdown: kramdown
markdown: CommonMarkGhPages
#theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
